### ISSUE TITLE
🐞 [Bug]: macro fails with lifetime bounds 

### ISSUE THREAD

**Issue by jkneer** [ozgunozerk/state-shift#28]
### What happened?

Macro will fail when using lifetime bounds on impl like impl<'a, 'b: 'a>.

### Expected behavior

should work :)

**Comment by ozgunozerk** [comment]
Thanks, nice catch! Seems like the code assumes the generic/lifetime bounds are placed in `where` clause, so it was generating errors when it is denoted with `'a: 'b` notation without a `where` clause.

**Comment by ozgunozerk** [comment]
Issued a new release 2.0.1
