### ISSUE TITLE
🐞 [Bug]: Explicit lifetime annotations are lost

### ISSUE THREAD

**Issue by jkneer** [ozgunozerk/state-shift#5]
### What happened?

impl and functions that are annotated by the state-shift macros lose the definitions of the explicit lifetimes.

### Expected behavior

Well lifetime definitions should be preserved.

**Comment by jkneer** [comment]
I have a use case for the typestate pattern outside of builders -  managing hardware devices. If we take your complex example the equivalent to my case would be the PlayerBuilder having a lifetime:
```rust 
#[type_state(state_slots = 3, default_state = Initial)]
struct PlayerBuilder<'forgiggles> {
    race: Option<Race>,
    level: Option<u8>,
    skill_slots: Option<u8>,
    spell_slots: Option<u8>,
    _lifetime: PhantomData<&'forgiggles ()>,
}
```

The type_state macro will strip the struct of that explicit lifetime. I haven't thought about the implications, but I think just conserving the lifetime is all it needs.

I'm sorry, I found this while playing with the pattern during a refactor. I would prefer not to delve into the depths of this crate :), though I'd be very happy to support the testing.

**Comment by ozgunozerk** [comment]
Thanks a lot! Yeah no worries I can fix it, already grateful to you for the issue report and the example code! You can track the updates from this issue 🚀

**Comment by jkneer** [comment]
Just tried the pattern in another section, where I would only need to hand a struct with a lifetime to the builders constructer. That also does not work, because it requires the Builder itself to define the lifetime, and that is currently not possible.

```rust
#[type_state(state_slots = 1, default_state = Initial)]
struct PlayerBuilder<'forgiggles> {
    myobject: MyObject<&'forgiggles ()>,
}

impl<'a> PlayerBuilder<'a> {
    #[require(Initial)]
    #[switch_to()...]
    fn new (obj: MyObject<'a>) {
        ...
    }
}
```

**Comment by jkneer** [comment]
Generally sounds like the right thing to do.

I'm a bit worried about
"it is reasonable to expect the user of this library to be consistent with the lifetime annotations between the struct and its associated methods." 
I agree that it is reasonable, but it is an additional requirement on the lifetime names, that is kind of arbitrary to the uninformed user of the lib. This has the potential to waste a lot of hours for users. Will the user get meaningfull error messages, or can it only be "fixed" by documentation? Yet I have no better idea on how to handle this.

**Comment by ozgunozerk** [comment]
> I'm a bit worried about
"it is reasonable to expect the user of this library to be consistent with the lifetime annotations between the struct and its associated methods."
I agree that it is reasonable, but it is an additional requirement on the lifetime names, that is kind of arbitrary to the uninformed user of the lib. This has the potential to waste a lot of hours for users. Will the user get meaningfull error messages, or can it only be "fixed" by documentation? Yet I have no better idea on how to handle this.

Totally agreed, will search for additional ways to provide meaningful error messages if possible. Otherwise it seems like documentation is our only bet

**Comment by ozgunozerk** [comment]
@jkneer great news, I think I implemented the requested feature and now it works. 

If you have time and still willing to test, could you please use the `generic-support` branch? 
You probably know this but you can easily select the branch of this crate in your cargo toml file using the git version.
```
state-shift = { git = "https://github.com/ozgunozerk/state-shift.git", branch = "generic-support" }
```
should be something like that.

Please let me know if there are any errors or potential improvements. Planning to open a PR and merge this feature soon

**Comment by jkneer** [comment]
Hi,

The lints on the lifetime seem to be gone, but two new things popped up:
- `where` clauses also seem to be lost. Fix is probably very similar to the lifetime fix.
- I have a 'type Result<T> = std::result::Result<T, MyError>' alias. On methods marked with **switch_to** these get linted with `type alias takes 1 generic argument but 2 generic arguments were supplied
expected 1 generic argument`. Looking at the expanded code it seems like the state is simply added as a generic to the Result; I think this would always break when a generic type is returned. The return probably needs to be wrapped instead of just expanding it?

Those two issues seem to be seperate issues and I would advise to move forward with this PR and create new issues for the return type and the where clause.

**Comment by ozgunozerk** [comment]
This is unexpected. I've tested `where` clauses in both the struct and the `impl` block. See this test file, which compiles fine: https://github.com/ozgunozerk/state-shift/blob/generic-support/tests/lifetime_example.rs

Reproducible example would be much appreciated if you can share the broken case and the code.

**Comment by ozgunozerk** [comment]
Wonderful! Let's continue from #9 as the next step 🚀
